name: Java CI
run-name: ${{ github.actor }} run tests
on: 
  pull_request:
    branches: 
    - main
jobs:
  build:
      runs-on: windows-latest
    
      steps:
      - uses: actions/checkout@v3
        name: setup JDK 17
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        run: chmod +x gradlew
      - name: Run the Gradle tests
        run: ./gradlew test --tests "*"
